package com.fictadvisor.android.utils

enum class StorageKeys {
    ACCESS_TOKEN,
    REFRESH_TOKEN,
    TELEGRAM_INFO,
    STUDENT_FIRST_NAME,
    STUDENT_MIDDLE_NAME,
    STUDENT_LAST_NAME,
    STUDENT_ID,
    STUDENT_USERNAME,
    STUDENT_EMAIL,
    STUDENT_AVATAR,
    STUDENT_TELEGRAM_ID,
    STUDENT_GROUP_ID,
    STUDENT_GROUP_CODE,
    STUDENT_GROUP_STATE,
    STUDENT_GROUP_ROLE,
}